local spells = {
  {ID = 1, Name_Lang_enUS = "Word of Recall (OLD)"},
  {ID = 3, Name_Lang_enUS = "Word of Mass Recall (OLD)"},
  {ID = 4, Name_Lang_enUS = "Word of Recall Other"},
  {ID = 5, Name_Lang_enUS = "Death Touch"},
  {ID = 7, Name_Lang_enUS = "Suicide"},
  {ID = 10, Name_Lang_enUS = "Blizzard"},
  {ID = 11, Name_Lang_enUS = "Frostbolt of Ages"},
  {ID = 12, Name_Lang_enUS = "Hot Foot (TEST)"},
  {ID = 13, Name_Lang_enUS = "Swim Speed (TEST)"},
  {ID = 14, Name_Lang_enUS = "Mana Drain"},
  {ID = 15, Name_Lang_enUS = "Leech (TEST)"},
  {ID = 17, Name_Lang_enUS = "Power Word: Shield"},
  {ID = 18, Name_Lang_enUS = "Heal Self (TEST)"},
  {ID = 22, Name_Lang_enUS = "Super Food (TEST)"},
  {ID = 24, Name_Lang_enUS = "Major Heal Self (TEST)"},
  {ID = 25, Name_Lang_enUS = "Stun"},
  {ID = 26, Name_Lang_enUS = "Bind Self (TEST)"},
  {ID = 27, Name_Lang_enUS = "Goldshire Portal"},
  {ID = 31, Name_Lang_enUS = "Teleport Goldshire"},
  {ID = 33, Name_Lang_enUS = "Teleport Westfall"},
  {ID = 34, Name_Lang_enUS = "Teleport Duskwood"},
  {ID = 35, Name_Lang_enUS = "Teleport Elwynn"},
  {ID = 43, Name_Lang_enUS = "Berserk"},
  {ID = 45, Name_Lang_enUS = "War Stomp"},
  {ID = 47, Name_Lang_enUS = "Sprint (TEST)"},
  {ID = 49, Name_Lang_enUS = "Heal 1000 (TEST)"},
  {ID = 50, Name_Lang_enUS = "Show Dot Variable"},
  {ID = 53, Name_Lang_enUS = "Backstab"},
  {ID = 56, Name_Lang_enUS = "Stun"},
  {ID = 58, Name_Lang_enUS = "Magic Missile (TEST)"},
  {ID = 59, Name_Lang_enUS = "Normal bow shot (TEST)"},
  {ID = 60, Name_Lang_enUS = "Long bow shot (TEST)"},
  {ID = 61, Name_Lang_enUS = "Really Long bow shot (TEST)"},
  {ID = 65, Name_Lang_enUS = "Haste"},
  {ID = 66, Name_Lang_enUS = "Invisibility"},
  {ID = 67, Name_Lang_enUS = "Vindication"},
  {ID = 68, Name_Lang_enUS = "Editor Test Spell"},
  {ID = 71, Name_Lang_enUS = "Defensive Stance"},
  {ID = 72, Name_Lang_enUS = "Shield Bash"},
  {ID = 75, Name_Lang_enUS = "Auto Shot"},
  {ID = 77, Name_Lang_enUS = "Turtle's Shell"},
  {ID = 78, Name_Lang_enUS = "Heroic Strike"},
  {ID = 81, Name_Lang_enUS = "Dodge"},
  {ID = 87, Name_Lang_enUS = "Automation Mechanic Immunity"},
  {ID = 89, Name_Lang_enUS = "Cripple"},
  {ID = 91, Name_Lang_enUS = "Savage Assault"},
  {ID = 96, Name_Lang_enUS = "Dismember"},
  {ID = 99, Name_Lang_enUS = "Demoralizing Roar"},
  {ID = 100, Name_Lang_enUS = "Charge"},
  {ID = 101, Name_Lang_enUS = "Trip"},
  {ID = 107, Name_Lang_enUS = "Block"},
  {ID = 108, Name_Lang_enUS = "Evade (DND)"},
  {ID = 110, Name_Lang_enUS = "Spell Deflection (NYI)"},
  {ID = 111, Name_Lang_enUS = "Time Step"},
  {ID = 112, Name_Lang_enUS = "Reflect Magic (TEST)"},
  {ID = 113, Name_Lang_enUS = "Chains of Ice"},
  {ID = 116, Name_Lang_enUS = "Frostbolt"},
  {ID = 118, Name_Lang_enUS = "Polymorph"},
  {ID = 120, Name_Lang_enUS = "Cone of Cold"},
  {ID = 122, Name_Lang_enUS = "Frost Nova"},
  {ID = 124, Name_Lang_enUS = "Holy Hand Grenade of the Resistance"},
  {ID = 126, Name_Lang_enUS = "Eye of Kilrogg"},
  {ID = 130, Name_Lang_enUS = "Slow Fall"},
  {ID = 131, Name_Lang_enUS = "Water Breathing"},
  {ID = 132, Name_Lang_enUS = "Detect Invisibility"},
  {ID = 133, Name_Lang_enUS = "Fireball"},
  {ID = 134, Name_Lang_enUS = "Fire Shield"},
  {ID = 136, Name_Lang_enUS = "Mend Pet"},
  {ID = 139, Name_Lang_enUS = "Renew"},
  {ID = 142, Name_Lang_enUS = "New Magic Missile (Test)"},
  {ID = 143, Name_Lang_enUS = "Fireball"},
  {ID = 145, Name_Lang_enUS = "Fireball"},
  {ID = 168, Name_Lang_enUS = "Frost Armor"},
  {ID = 172, Name_Lang_enUS = "Corruption"},
  {ID = 184, Name_Lang_enUS = "Fire Shield II"},
  {ID = 196, Name_Lang_enUS = "One-Handed Axes"},
  {ID = 197, Name_Lang_enUS = "Two-Handed Axes"},
  {ID = 198, Name_Lang_enUS = "One-Handed Maces"},
  {ID = 199, Name_Lang_enUS = "Two-Handed Maces"},
  {ID = 200, Name_Lang_enUS = "Polearms"},
  {ID = 201, Name_Lang_enUS = "One-Handed Swords"},
  {ID = 202, Name_Lang_enUS = "Two-Handed Swords"},
  {ID = 203, Name_Lang_enUS = "Unarmed"},
  {ID = 204, Name_Lang_enUS = "Defense"},
  {ID = 205, Name_Lang_enUS = "Frostbolt"},
  {ID = 227, Name_Lang_enUS = "Staves"},
  {ID = 228, Name_Lang_enUS = "Polymorph: Chicken"},
  {ID = 246, Name_Lang_enUS = "Slow"},
  {ID = 260, Name_Lang_enUS = "Charm (TEST)"},
  {ID = 261, Name_Lang_enUS = "Summon Skeleton"},
  {ID = 264, Name_Lang_enUS = "Bows"},
  {ID = 265, Name_Lang_enUS = "Area Death (TEST)"},
  {ID = 266, Name_Lang_enUS = "Guns"},
  {ID = 269, Name_Lang_enUS = "Walk of Fire Trigger (DNC)"},
  {ID = 271, Name_Lang_enUS = "Call of the Void"},
  {ID = 284, Name_Lang_enUS = "Heroic Strike"},
  {ID = 285, Name_Lang_enUS = "Heroic Strike"},
  {ID = 324, Name_Lang_enUS = "Lightning Shield"},
  {ID = 325, Name_Lang_enUS = "Lightning Shield"},
  {ID = 331, Name_Lang_enUS = "Healing Wave"},
  {ID = 332, Name_Lang_enUS = "Healing Wave"},
  {ID = 339, Name_Lang_enUS = "Entangling Roots"},
  {ID = 348, Name_Lang_enUS = "Immolate"},
  {ID = 355, Name_Lang_enUS = "Taunt"},
  {ID = 370, Name_Lang_enUS = "Purge"},
  {ID = 379, Name_Lang_enUS = "Earth Shield"},
  {ID = 403, Name_Lang_enUS = "Lightning Bolt"},
  {ID = 408, Name_Lang_enUS = "Kidney Shot"},
  {ID = 421, Name_Lang_enUS = "Chain Lightning"},
  {ID = 427, Name_Lang_enUS = "Teleport Monastery"},
  {ID = 428, Name_Lang_enUS = "Teleport Moonbrook"},
  {ID = 430, Name_Lang_enUS = "Drink"},
  {ID = 431, Name_Lang_enUS = "Drink"},
  {ID = 432, Name_Lang_enUS = "Drink"},
  {ID = 433, Name_Lang_enUS = "Food"},
  {ID = 434, Name_Lang_enUS = "Food"},
  {ID = 435, Name_Lang_enUS = "Food"},
  {ID = 436, Name_Lang_enUS = "Restore Mana"},
  {ID = 437, Name_Lang_enUS = "Restore Mana"},
  {ID = 438, Name_Lang_enUS = "Restore Mana"},
  {ID = 439, Name_Lang_enUS = "Healing Potion"},
  {ID = 440, Name_Lang_enUS = "Healing Potion"},
  {ID = 441, Name_Lang_enUS = "Healing Potion"},
  {ID = 442, Name_Lang_enUS = "Teleport Northshire Abbey"},
  {ID = 443, Name_Lang_enUS = "Teleport Barracks"},
  {ID = 444, Name_Lang_enUS = "Teleport Lighthouse"},
  {ID = 445, Name_Lang_enUS = "Teleport Darkshire"},
  {ID = 446, Name_Lang_enUS = "Teleport Cemetary"},
  {ID = 447, Name_Lang_enUS = "Teleport Treant"},
  {ID = 448, Name_Lang_enUS = "Editor test spell 2"},
  {ID = 453, Name_Lang_enUS = "Mind Soothe"},
  {ID = 454, Name_Lang_enUS = "Gallop (TEST)"},
  {ID = 456, Name_Lang_enUS = "SHOWLABEL Only OFF"},
  {ID = 457, Name_Lang_enUS = "Feeblemind"},
  {ID = 458, Name_Lang_enUS = "Brown Horse"},
  {ID = 459, Name_Lang_enUS = "Gray Wolf"},
  {ID = 461, Name_Lang_enUS = "Righteous Flame On"},
  {ID = 463, Name_Lang_enUS = "Aura Overlap TEST 1"},
  {ID = 464, Name_Lang_enUS = "Aura Overlap TEST 2"},
  {ID = 465, Name_Lang_enUS = "Devotion Aura"},
  {ID = 467, Name_Lang_enUS = "Thorns"},
  {ID = 468, Name_Lang_enUS = "White Stallion"},
  {ID = 469, Name_Lang_enUS = "Commanding Shout"},
  {ID = 470, Name_Lang_enUS = "Black Stallion"},
  {ID = 471, Name_Lang_enUS = "Palamino"},
  {ID = 472, Name_Lang_enUS = "Pinto"},
  {ID = 475, Name_Lang_enUS = "Remove Curse"},
  {ID = 483, Name_Lang_enUS = "Learning"},
  {ID = 491, Name_Lang_enUS = "Khadgar's Unlocking"},
  {ID = 498, Name_Lang_enUS = "Divine Protection"},
  {ID = 512, Name_Lang_enUS = "Chains of Ice"},
  {ID = 514, Name_Lang_enUS = "Wyatt Test"},
  {ID = 518, Name_Lang_enUS = "Summon Worm"},
  {ID = 522, Name_Lang_enUS = "SPELLDEFENSE (DND)"},
  {ID = 526, Name_Lang_enUS = "Cure Toxins"},
  {ID = 527, Name_Lang_enUS = "Dispel Magic"},
  {ID = 528, Name_Lang_enUS = "Cure Disease"},
  {ID = 529, Name_Lang_enUS = "Lightning Bolt"},
  {ID = 530, Name_Lang_enUS = "Charm (Possess)"},
  {ID = 543, Name_Lang_enUS = "Fire Ward"},
  {ID = 546, Name_Lang_enUS = "Water Walking"},
  {ID = 547, Name_Lang_enUS = "Healing Wave"},
  {ID = 548, Name_Lang_enUS = "Lightning Bolt"},
  {ID = 550, Name_Lang_enUS = "Nullify Poison"},
  {ID = 552, Name_Lang_enUS = "Abolish Disease"},
  {ID = 553, Name_Lang_enUS = "Wavestorm 2"},
  {ID = 555, Name_Lang_enUS = "Feral Spirit"},
  {ID = 556, Name_Lang_enUS = "Astral Recall"},
  {ID = 563, Name_Lang_enUS = "Moonfire"},
  {ID = 568, Name_Lang_enUS = "Arcane Burst"},
  {ID = 578, Name_Lang_enUS = "Black Wolf"},
  {ID = 579, Name_Lang_enUS = "Red Wolf"},
  {ID = 580, Name_Lang_enUS = "Timber Wolf"},
  {ID = 581, Name_Lang_enUS = "Winter Wolf"},
  {ID = 585, Name_Lang_enUS = "Smite"},
  {ID = 586, Name_Lang_enUS = "Fade"},
  {ID = 587, Name_Lang_enUS = "Conjure Food"},
  {ID = 588, Name_Lang_enUS = "Inner Fire"},
  {ID = 589, Name_Lang_enUS = "Shadow Word: Pain"},
  {ID = 591, Name_Lang_enUS = "Smite"},
  {ID = 592, Name_Lang_enUS = "Power Word: Shield"},
  {ID = 594, Name_Lang_enUS = "Shadow Word: Pain"},
  {ID = 596, Name_Lang_enUS = "Prayer of Healing"},
  {ID = 597, Name_Lang_enUS = "Conjure Food"},
  {ID = 598, Name_Lang_enUS = "Smite"},
  {ID = 600, Name_Lang_enUS = "Power Word: Shield"},
  {ID = 601, Name_Lang_enUS = "Sword Mastery"},
  {ID = 602, Name_Lang_enUS = "Inner Fire"},
  {ID = 603, Name_Lang_enUS = "Curse of Doom"},
  {ID = 604, Name_Lang_enUS = "Dampen Magic"},
  {ID = 605, Name_Lang_enUS = "Mind Control"},
  {ID = 606, Name_Lang_enUS = "Mind Rot"},
  {ID = 633, Name_Lang_enUS = "Lay on Hands"},
  {ID = 635, Name_Lang_enUS = "Holy Light"},
  {ID = 639, Name_Lang_enUS = "Holy Light"},
  {ID = 642, Name_Lang_enUS = "Divine Shield"},
  {ID = 643, Name_Lang_enUS = "Devotion Aura"},
  {ID = 647, Name_Lang_enUS = "Holy Light"},
  {ID = 668, Name_Lang_enUS = "Language Common"},
  {ID = 669, Name_Lang_enUS = "Language Orcish"},
  {ID = 670, Name_Lang_enUS = "Language Taurahe"},
  {ID = 671, Name_Lang_enUS = "Language Darnassian"},
  {ID = 672, Name_Lang_enUS = "Language Dwarven"},
  {ID = 673, Name_Lang_enUS = "Lesser Armor"},
  {ID = 674, Name_Lang_enUS = "Dual Wield"},
  {ID = 676, Name_Lang_enUS = "Disarm"},
  {ID = 686, Name_Lang_enUS = "Shadow Bolt"},
  {ID = 687, Name_Lang_enUS = "Demon Skin"},
  {ID = 688, Name_Lang_enUS = "Summon Imp"},
  {ID = 689, Name_Lang_enUS = "Drain Life"},
  {ID = 691, Name_Lang_enUS = "Summon Felhunter"},
  {ID = 692, Name_Lang_enUS = "Terror (TEST)"},
  {ID = 693, Name_Lang_enUS = "Create Soulstone"},
  {ID = 694, Name_Lang_enUS = "Mocking Blow"},
  {ID = 695, Name_Lang_enUS = "Shadow Bolt"},
  {ID = 696, Name_Lang_enUS = "Demon Skin"},
  {ID = 697, Name_Lang_enUS = "Summon Voidwalker"},
  {ID = 698, Name_Lang_enUS = "Ritual of Summoning"},
  {ID = 699, Name_Lang_enUS = "Drain Life"},
  {ID = 700, Name_Lang_enUS = "Sleep"},
  {ID = 701, Name_Lang_enUS = "Firebolt"},
  {ID = 702, Name_Lang_enUS = "Curse of Weakness"},
  {ID = 703, Name_Lang_enUS = "Garrote"},
  {ID = 705, Name_Lang_enUS = "Shadow Bolt"},
  {ID = 706, Name_Lang_enUS = "Demon Armor"},
  {ID = 707, Name_Lang_enUS = "Immolate"},
  {ID = 709, Name_Lang_enUS = "Drain Life"},
  {ID = 710, Name_Lang_enUS = "Banish"},
  {ID = 712, Name_Lang_enUS = "Summon Succubus"},
  {ID = 720, Name_Lang_enUS = "Entangle"},
  {ID = 724, Name_Lang_enUS = "Lightwell"},
  {ID = 731, Name_Lang_enUS = "Entangle"},
  {ID = 739, Name_Lang_enUS = "Debuff Fire Resist (TEST)"},
  {ID = 740, Name_Lang_enUS = "Tranquility"},
  {ID = 742, Name_Lang_enUS = "Pulverize"},
  {ID = 744, Name_Lang_enUS = "Poison"},
  {ID = 745, Name_Lang_enUS = "Web"},
  {ID = 746, Name_Lang_enUS = "First Aid"},
  {ID = 747, Name_Lang_enUS = "Summon Images"},
  {ID = 750, Name_Lang_enUS = "Plate Mail"},
  {ID = 755, Name_Lang_enUS = "Health Funnel"},
  {ID = 759, Name_Lang_enUS = "Conjure Mana Gem"},
  {ID = 768, Name_Lang_enUS = "Cat Form"},
  {ID = 769, Name_Lang_enUS = "Swipe (Bear)"},
  {ID = 770, Name_Lang_enUS = "Faerie Fire"},
  {ID = 772, Name_Lang_enUS = "Rend"},
  {ID = 774, Name_Lang_enUS = "Rejuvenation"},
  {ID = 779, Name_Lang_enUS = "Swipe (Bear)"},
  {ID = 780, Name_Lang_enUS = "Swipe (Bear)"},
  {ID = 781, Name_Lang_enUS = "Disengage"},
  {ID = 782, Name_Lang_enUS = "Thorns"},
  {ID = 783, Name_Lang_enUS = "Travel Form"},
  {ID = 785, Name_Lang_enUS = "True Fulfillment"},
  {ID = 799, Name_Lang_enUS = "Twin Teleport"},
  {ID = 800, Name_Lang_enUS = "Twin Teleport"},
  {ID = 802, Name_Lang_enUS = "Mutate Bug"},
  {ID = 804, Name_Lang_enUS = "Explode Bug"},
  {ID = 806, Name_Lang_enUS = "Fervor"},
  {ID = 812, Name_Lang_enUS = "Periodic Mana Burn"},
  {ID = 813, Name_Lang_enUS = "Language Thalassian"},
  {ID = 814, Name_Lang_enUS = "Language Draconic"},
  {ID = 815, Name_Lang_enUS = "Language Demon Tongue"},
  {ID = 816, Name_Lang_enUS = "Language Titan"},
  {ID = 817, Name_Lang_enUS = "Language Old Tongue (NYI)"},
  {ID = 818, Name_Lang_enUS = "Basic Campfire"},
  {ID = 822, Name_Lang_enUS = "Magic Resistance"},
  {ID = 823, Name_Lang_enUS = "Natural Resistance"},
  {ID = 824, Name_Lang_enUS = "Horse Riding"},
  {ID = 825, Name_Lang_enUS = "Wolf Riding"},
  {ID = 826, Name_Lang_enUS = "Ram Riding"},
  {ID = 827, Name_Lang_enUS = "Nightmare Riding"},
  {ID = 828, Name_Lang_enUS = "Tiger Riding"},
  {ID = 829, Name_Lang_enUS = "Thickskull"},
  {ID = 830, Name_Lang_enUS = "Fearless"},
  {ID = 831, Name_Lang_enUS = "Swimming (NYI)"},
  {ID = 833, Name_Lang_enUS = "Green Tea"},
  {ID = 834, Name_Lang_enUS = "Lesser Armor"},
  {ID = 835, Name_Lang_enUS = "Tidal Charm"},
  {ID = 836, Name_Lang_enUS = "LOGINEFFECT"},
  {ID = 837, Name_Lang_enUS = "Frostbolt"},
  {ID = 845, Name_Lang_enUS = "Cleave"},
  {ID = 851, Name_Lang_enUS = "Polymorph: Sheep"},
  {ID = 853, Name_Lang_enUS = "Hammer of Justice"},
  {ID = 857, Name_Lang_enUS = "Khadgar's Unlocking"},
  {ID = 865, Name_Lang_enUS = "Frost Nova"},
  {ID = 871, Name_Lang_enUS = "Shield Wall"},
  {ID = 879, Name_Lang_enUS = "Exorcism"},
  {ID = 883, Name_Lang_enUS = "Call Pet"},
  {ID = 897, Name_Lang_enUS = "Summon Angry Programmer"},
  {ID = 898, Name_Lang_enUS = "Create Fervor Potion"},
  {ID = 905, Name_Lang_enUS = "Lightning Shield"},
  {ID = 913, Name_Lang_enUS = "Healing Wave"},
  {ID = 915, Name_Lang_enUS = "Lightning Bolt"},
  {ID = 921, Name_Lang_enUS = "Pick Pocket"},
  {ID = 930, Name_Lang_enUS = "Chain Lightning"},
  {ID = 932, Name_Lang_enUS = "Replenish Spirit II"},
  {ID = 939, Name_Lang_enUS = "Healing Wave"},
  {ID = 943, Name_Lang_enUS = "Lightning Bolt"},
  {ID = 945, Name_Lang_enUS = "Lightning Shield"},
  {ID = 952, Name_Lang_enUS = "Glacier"},
  {ID = 959, Name_Lang_enUS = "Healing Wave"},
  {ID = 970, Name_Lang_enUS = "Shadow Word: Pain"},
  {ID = 974, Name_Lang_enUS = "Earth Shield"},
  {ID = 976, Name_Lang_enUS = "Shadow Protection"},
  {ID = 980, Name_Lang_enUS = "Curse of Agony"},
  {ID = 982, Name_Lang_enUS = "Revive Pet"},
  {ID = 984, Name_Lang_enUS = "Smite"},
  {ID = 988, Name_Lang_enUS = "Dispel Magic"},
  {ID = 990, Name_Lang_enUS = "Conjure Food"},
  {ID = 992, Name_Lang_enUS = "Shadow Word: Pain"},
  {ID = 996, Name_Lang_enUS = "Prayer of Healing"},
  {ID = 1002, Name_Lang_enUS = "Eyes of the Beast"},
  {ID = 1004, Name_Lang_enUS = "Smite"},
  {ID = 1006, Name_Lang_enUS = "Inner Fire"},
  {ID = 1008, Name_Lang_enUS = "Amplify Magic"},
  {ID = 1010, Name_Lang_enUS = "Curse of Idiocy"},
  {ID = 1014, Name_Lang_enUS = "Curse of Agony"},
  {ID = 1022, Name_Lang_enUS = "Hand of Protection"},
  {ID = 1026, Name_Lang_enUS = "Holy Light"},
  {ID = 1032, Name_Lang_enUS = "Devotion Aura"},
  {ID = 1035, Name_Lang_enUS = "Fire Ward"},
  {ID = 1038, Name_Lang_enUS = "Hand of Salvation"},
  {ID = 1042, Name_Lang_enUS = "Holy Light"},
  {ID = 1044, Name_Lang_enUS = "Hand of Freedom"},
  {ID = 1050, Name_Lang_enUS = "Sacrifice"},
  {ID = 1058, Name_Lang_enUS = "Rejuvenation"},
  {ID = 1062, Name_Lang_enUS = "Entangling Roots"},
  {ID = 1064, Name_Lang_enUS = "Chain Heal"},
  {ID = 1066, Name_Lang_enUS = "Aquatic Form"},
  {ID = 1075, Name_Lang_enUS = "Thorns"},
  {ID = 1079, Name_Lang_enUS = "Rip"},
  {ID = 1082, Name_Lang_enUS = "Claw"},
  {ID = 1086, Name_Lang_enUS = "Demon Armor"},
  {ID = 1088, Name_Lang_enUS = "Shadow Bolt"},
  {ID = 1090, Name_Lang_enUS = "Sleep"},
  {ID = 1094, Name_Lang_enUS = "Immolate"},
  {ID = 1098, Name_Lang_enUS = "Enslave Demon"},
  {ID = 1106, Name_Lang_enUS = "Shadow Bolt"},
  {ID = 1108, Name_Lang_enUS = "Curse of Weakness"},
  {ID = 1120, Name_Lang_enUS = "Drain Soul"},
  {ID = 1121, Name_Lang_enUS = "Entangle"},
  {ID = 1122, Name_Lang_enUS = "Inferno"},
  {ID = 1126, Name_Lang_enUS = "Mark of the Wild"},
  {ID = 1127, Name_Lang_enUS = "Food"},
  {ID = 1129, Name_Lang_enUS = "Food"},
  {ID = 1130, Name_Lang_enUS = "Hunter's Mark"},
  {ID = 1131, Name_Lang_enUS = "Food"},
  {ID = 1132, Name_Lang_enUS = "Critical Strike"},
  {ID = 1133, Name_Lang_enUS = "Drink"},
  {ID = 1135, Name_Lang_enUS = "Drink"},
  {ID = 1137, Name_Lang_enUS = "Drink"},
  {ID = 1138, Name_Lang_enUS = "Crystal Protection"},
  {ID = 1139, Name_Lang_enUS = "Cold Eye"},
  {ID = 1152, Name_Lang_enUS = "Purify"},
  {ID = 1159, Name_Lang_enUS = "First Aid"},
  {ID = 1160, Name_Lang_enUS = "Demoralizing Shout"},
  {ID = 1161, Name_Lang_enUS = "Challenging Shout"},
  {ID = 1178, Name_Lang_enUS = "Bear Form (Passive)"},
  {ID = 1180, Name_Lang_enUS = "Daggers"},
  {ID = 1194, Name_Lang_enUS = "Frost Nova"},
  {ID = 1196, Name_Lang_enUS = "Blizzard"},
  {ID = 1210, Name_Lang_enUS = "Conjure Mana Gem"},
  {ID = 1214, Name_Lang_enUS = "Ice Armor"},
  {ID = 1225, Name_Lang_enUS = "Frost Nova"},
  {ID = 1228, Name_Lang_enUS = "Ice Armor"},
  {ID = 1234, Name_Lang_enUS = "Brilliance Aura IV"},
  {ID = 1241, Name_Lang_enUS = "Cone of Cold"},
  {ID = 1243, Name_Lang_enUS = "Power Word: Fortitude"},
  {ID = 1244, Name_Lang_enUS = "Power Word: Fortitude"},
  {ID = 1245, Name_Lang_enUS = "Power Word: Fortitude"},
  {ID = 1249, Name_Lang_enUS = "Conjure Food"},
  {ID = 1250, Name_Lang_enUS = "Conjure Food"},
  {ID = 1251, Name_Lang_enUS = "Conjure Food"},
  {ID = 1266, Name_Lang_enUS = "Dampen Magic"},
  {ID = 1267, Name_Lang_enUS = "Amplify Magic"},
  {ID = 1302, Name_Lang_enUS = "Damage Immunity Test"},
  {ID = 1329, Name_Lang_enUS = "Mutilate"},
  {ID = 1330, Name_Lang_enUS = "Garrote - Silence"},
  {ID = 1350, Name_Lang_enUS = "Feral Spirit"},
  {ID = 1364, Name_Lang_enUS = "Unyielding Will"},
  {ID = 1373, Name_Lang_enUS = "Teach Summon Felhunter"},
  {ID = 1386, Name_Lang_enUS = "Echoes of Lordaeron"},
  {ID = 1413, Name_Lang_enUS = "Inferno"},
  {ID = 1430, Name_Lang_enUS = "Rejuvenation"},
  {ID = 1446, Name_Lang_enUS = "Aquatic Form"},
  {ID = 1449, Name_Lang_enUS = "Arcane Explosion"},
  {ID = 1454, Name_Lang_enUS = "Life Tap"},
  {ID = 1455, Name_Lang_enUS = "Life Tap"},
  {ID = 1456, Name_Lang_enUS = "Life Tap"},
  {ID = 1459, Name_Lang_enUS = "Arcane Intellect"},
  {ID = 1460, Name_Lang_enUS = "Arcane Intellect"},
  {ID = 1461, Name_Lang_enUS = "Arcane Intellect"},
  {ID = 1462, Name_Lang_enUS = "Beast Lore"},
  {ID = 1463, Name_Lang_enUS = "Mana Shield"},
  {ID = 1464, Name_Lang_enUS = "Slam"},
  {ID = 1467, Name_Lang_enUS = "Arcane Explosion"},
  {ID = 1472, Name_Lang_enUS = "Arcane Intellect"},
  {ID = 1473, Name_Lang_enUS = "Arcane Intellect"},
  {ID = 1474, Name_Lang_enUS = "Arcane Intellect"},
  {ID = 1475, Name_Lang_enUS = "Arcane Intellect"},
  {ID = 1481, Name_Lang_enUS = "Mana Shield"},
  {ID = 1485, Name_Lang_enUS = "Metawheel Boulder"},
  {ID = 1490, Name_Lang_enUS = "Curse of the Elements"},
  {ID = 1494, Name_Lang_enUS = "Track Beasts"},
  {ID = 1495, Name_Lang_enUS = "Mongoose Bite"},
  {ID = 1499, Name_Lang_enUS = "Freezing Trap"},
  {ID = 1509, Name_Lang_enUS = "GM Only OFF"},
  {ID = 1510, Name_Lang_enUS = "Volley"},
  {ID = 1513, Name_Lang_enUS = "Scare Beast"},
  {ID = 1515, Name_Lang_enUS = "Tame Beast"},
  {ID = 1516, Name_Lang_enUS = "Quick Shot"},
  {ID = 1522, Name_Lang_enUS = "Pet Upgrade (NYI)"},
  {ID = 1528, Name_Lang_enUS = "Free Master"},
  {ID = 1535, Name_Lang_enUS = "Fire Nova"},
  {ID = 1536, Name_Lang_enUS = "Longshot II"},
  {ID = 1538, Name_Lang_enUS = "Charging"},
  {ID = 1539, Name_Lang_enUS = "Feed Pet"},
  {ID = 1543, Name_Lang_enUS = "Flare"},
  {ID = 1557, Name_Lang_enUS = "Full Speed"},
  {ID = 1579, Name_Lang_enUS = "Tame Beast"},
  {ID = 1588, Name_Lang_enUS = "Pet Upgrade"},
  {ID = 1604, Name_Lang_enUS = "Dazed"},
  {ID = 1608, Name_Lang_enUS = "Heroic Strike"},
  {ID = 1609, Name_Lang_enUS = "Ashbringer Buzzsaw"},
  {ID = 1650, Name_Lang_enUS = "Slowing Strike III"},
  {ID = 1664, Name_Lang_enUS = "Savage Assault IV"},
  {ID = 1665, Name_Lang_enUS = "Savage Assault V"},
  {ID = 1666, Name_Lang_enUS = "Savage Assault"},
  {ID = 1669, Name_Lang_enUS = "Savage Assault IV"},
  {ID = 1671, Name_Lang_enUS = "Shield Bash"},
  {ID = 1672, Name_Lang_enUS = "Shield Bash"},
  {ID = 1680, Name_Lang_enUS = "Whirlwind"},
  {ID = 1706, Name_Lang_enUS = "Levitate"},
  {ID = 1710, Name_Lang_enUS = "Summon Felsteed"},
  {ID = 1714, Name_Lang_enUS = "Curse of Tongues"},
  {ID = 1715, Name_Lang_enUS = "Hamstring"},
  {ID = 1719, Name_Lang_enUS = "Recklessness"},
  {ID = 1725, Name_Lang_enUS = "Distract"},
  {ID = 1735, Name_Lang_enUS = "Demoralizing Roar"},
  {ID = 1742, Name_Lang_enUS = "Cower"},
  {ID = 1747, Name_Lang_enUS = "Cower"},
  {ID = 1748, Name_Lang_enUS = "Cower"},
  {ID = 1749, Name_Lang_enUS = "Cower"},
  {ID = 1750, Name_Lang_enUS = "Cower"},
  {ID = 1751, Name_Lang_enUS = "Cower"},
  {ID = 1752, Name_Lang_enUS = "Sinister Strike"},
  {ID = 1753, Name_Lang_enUS = "Cower"},
  {ID = 1754, Name_Lang_enUS = "Cower"},
  {ID = 1755, Name_Lang_enUS = "Cower"},
  {ID = 1756, Name_Lang_enUS = "Cower"},
  {ID = 1757, Name_Lang_enUS = "Sinister Strike"},
  {ID = 1758, Name_Lang_enUS = "Sinister Strike"},
  {ID = 1759, Name_Lang_enUS = "Sinister Strike"},
  {ID = 1760, Name_Lang_enUS = "Sinister Strike"},
  {ID = 1766, Name_Lang_enUS = "Kick"},
  {ID = 1767, Name_Lang_enUS = "Kick"},
  {ID = 1768, Name_Lang_enUS = "Kick"},
  {ID = 1769, Name_Lang_enUS = "Kick"},
  {ID = 1770, Name_Lang_enUS = "Kick"},
  {ID = 1776, Name_Lang_enUS = "Gouge"},
  {ID = 1777, Name_Lang_enUS = "Gouge"},
  {ID = 1784, Name_Lang_enUS = "Stealth"},
  {ID = 1785, Name_Lang_enUS = "Stealth"},
  {ID = 1786, Name_Lang_enUS = "Stealth"},
  {ID = 1787, Name_Lang_enUS = "Stealth"},
  {ID = 1795, Name_Lang_enUS = "Disheartening Blow II"},
  {ID = 1796, Name_Lang_enUS = "Disheartening Blow III"},
  {ID = 1797, Name_Lang_enUS = "Disheartening Blow IV"},
  {ID = 1798, Name_Lang_enUS = "Disheartening Blow V"},
  {ID = 1800, Name_Lang_enUS = "Disheartening Blow II"},
  {ID = 1804, Name_Lang_enUS = "Pick Lock"},
  {ID = 1809, Name_Lang_enUS = "Lockpicking"},
  {ID = 1810, Name_Lang_enUS = "Lockpicking"},
  {ID = 1811, Name_Lang_enUS = "Scorch"},
  {ID = 1822, Name_Lang_enUS = "Rake"},
  {ID = 1823, Name_Lang_enUS = "Rake"},
  {ID = 1824, Name_Lang_enUS = "Rake"},
  {ID = 1825, Name_Lang_enUS = "Lend Pet (NYI)"},
  {ID = 1831, Name_Lang_enUS = "Blast Wave"},
  {ID = 1833, Name_Lang_enUS = "Cheap Shot"},
  {ID = 1834, Name_Lang_enUS = "Gathering Speed"},
  {ID = 1842, Name_Lang_enUS = "Disarm Trap"},
  {ID = 1843, Name_Lang_enUS = "Disarm"},
  {ID = 1844, Name_Lang_enUS = "Disarming Fury Effect"},
  {ID = 1848, Name_Lang_enUS = "Divining Chant"},
  {ID = 1850, Name_Lang_enUS = "Dash"},
  {ID = 1852, Name_Lang_enUS = "Silenced"},
  {ID = 1853, Name_Lang_enUS = "Growl"},
  {ID = 1856, Name_Lang_enUS = "Vanish"},
  {ID = 1857, Name_Lang_enUS = "Vanish"},
  {ID = 1860, Name_Lang_enUS = "Safe Fall"},
  {ID = 1881, Name_Lang_enUS = "Summon Hive'Zara Hatchling"},
  {ID = 1906, Name_Lang_enUS = "Debilitating Charge"},
  {ID = 1908, Name_Lang_enUS = "Uber Heal Over Time"},
  {ID = 1936, Name_Lang_enUS = "Teleport Anvilmar"},
  {ID = 1940, Name_Lang_enUS = "Rocket Blast"},
  {ID = 1943, Name_Lang_enUS = "Rupture"},
  {ID = 1949, Name_Lang_enUS = "Hellfire"},
  {ID = 1950, Name_Lang_enUS = "Greater Shadow Imp"},
  {ID = 1953, Name_Lang_enUS = "Blink"},
  {ID = 1966, Name_Lang_enUS = "Feint"},
  {ID = 1978, Name_Lang_enUS = "Serpent Sting"},
  {ID = 1991, Name_Lang_enUS = "Scatter Shot IV"},
  {ID = 2000, Name_Lang_enUS = "Head Shot"},
  {ID = 2006, Name_Lang_enUS = "Resurrection"},
  {ID = 2008, Name_Lang_enUS = "Ancestral Spirit"},
  {ID = 2010, Name_Lang_enUS = "Resurrection"},
  {ID = 2018, Name_Lang_enUS = "Blacksmithing"},
  {ID = 2020, Name_Lang_enUS = "Apprentice Blacksmith"},
  {ID = 2021, Name_Lang_enUS = "Journeyman Blacksmith"},
  {ID = 2023, Name_Lang_enUS = "Restore Mana"},
  {ID = 2024, Name_Lang_enUS = "Healing Potion"},
  {ID = 2048, Name_Lang_enUS = "Battle Shout"},
  {ID = 2050, Name_Lang_enUS = "Lesser Heal"},
  {ID = 2052, Name_Lang_enUS = "Lesser Heal"},
  {ID = 2053, Name_Lang_enUS = "Lesser Heal"},
  {ID = 2054, Name_Lang_enUS = "Heal"},
  {ID = 2055, Name_Lang_enUS = "Heal"},
  {ID = 2060, Name_Lang_enUS = "Greater Heal"},
  {ID = 2061, Name_Lang_enUS = "Flash Heal"},
  {ID = 2062, Name_Lang_enUS = "Earth Elemental Totem"},
  {ID = 2070, Name_Lang_enUS = "Sap"},
  {ID = 2075, Name_Lang_enUS = "Searing Totem"},
  {ID = 2090, Name_Lang_enUS = "Rejuvenation"},
  {ID = 2091, Name_Lang_enUS = "Rejuvenation"},
  {ID = 2094, Name_Lang_enUS = "Blind"},
  {ID = 2096, Name_Lang_enUS = "Mind Vision"},
  {ID = 2098, Name_Lang_enUS = "Eviscerate"},
  {ID = 2108, Name_Lang_enUS = "Leatherworking"},
  {ID = 2110, Name_Lang_enUS = "FIRESTAFF (DND)"},
  {ID = 2118, Name_Lang_enUS = "Dodge Mastery"},
  {ID = 2119, Name_Lang_enUS = "Nature Resist"},
  {ID = 2120, Name_Lang_enUS = "Flamestrike"},
  {ID = 2121, Name_Lang_enUS = "Flamestrike"},
  {ID = 2123, Name_Lang_enUS = "Holy Affinity"},
  {ID = 2124, Name_Lang_enUS = "Flamestrike"},
  {ID = 2125, Name_Lang_enUS = "Flamestrike"},
  {ID = 2136, Name_Lang_enUS = "Fire Blast"},
  {ID = 2137, Name_Lang_enUS = "Fire Blast"},
  {ID = 2138, Name_Lang_enUS = "Fire Blast"},
  {ID = 2139, Name_Lang_enUS = "Counterspell"},
  {ID = 2140, Name_Lang_enUS = "Stasis Effect"},
  {ID = 2141, Name_Lang_enUS = "Fire Blast"},
  {ID = 2142, Name_Lang_enUS = "Fire Blast"},
  {ID = 2143, Name_Lang_enUS = "Fire Blast"},
  {ID = 2147, Name_Lang_enUS = "Mending"},
  {ID = 2148, Name_Lang_enUS = "Periodic Shadow Storm"},
  {ID = 2149, Name_Lang_enUS = "Handstitched Leather Boots"},
  {ID = 2152, Name_Lang_enUS = "Light Armor Kit"},
  {ID = 2153, Name_Lang_enUS = "Handstitched Leather Pants"},
  {ID = 2154, Name_Lang_enUS = "Journeyman Leatherworker"},
  {ID = 2155, Name_Lang_enUS = "Apprentice Leatherworker"},
  {ID = 2156, Name_Lang_enUS = "Light Winter Cloak"},
  {ID = 2157, Name_Lang_enUS = "Light Winter Boots"},
  {ID = 2158, Name_Lang_enUS = "Fine Leather Boots"},
  {ID = 2159, Name_Lang_enUS = "Fine Leather Cloak"},
  {ID = 2160, Name_Lang_enUS = "Embossed Leather Vest"},
  {ID = 2161, Name_Lang_enUS = "Embossed Leather Boots"},
  {ID = 2162, Name_Lang_enUS = "Embossed Leather Cloak"},
  {ID = 2163, Name_Lang_enUS = "White Leather Jerkin"},
  {ID = 2164, Name_Lang_enUS = "Fine Leather Gloves"},
  {ID = 2165, Name_Lang_enUS = "Medium Armor Kit"},
  {ID = 2166, Name_Lang_enUS = "Toughened Leather Armor"},
  {ID = 2167, Name_Lang_enUS = "Dark Leather Boots"},
  {ID = 2168, Name_Lang_enUS = "Dark Leather Cloak"},
  {ID = 2169, Name_Lang_enUS = "Dark Leather Tunic"},
  {ID = 2222, Name_Lang_enUS = "Portal Storm"},
  {ID = 2259, Name_Lang_enUS = "Alchemy"},
  {ID = 2275, Name_Lang_enUS = "Apprentice Alchemist"},
  {ID = 2280, Name_Lang_enUS = "Journeyman Alchemist"},
  {ID = 2313, Name_Lang_enUS = "True Fulfillment"},
  {ID = 2329, Name_Lang_enUS = "Elixir of Lion's Strength"},
  {ID = 2330, Name_Lang_enUS = "Minor Healing Potion"},
  {ID = 2331, Name_Lang_enUS = "Minor Mana Potion"},
  {ID = 2332, Name_Lang_enUS = "Minor Rejuvenation Potion"},
  {ID = 2333, Name_Lang_enUS = "Elixir of Lesser Agility"},
  {ID = 2334, Name_Lang_enUS = "Elixir of Minor Fortitude"},
  {ID = 2335, Name_Lang_enUS = "Swiftness Potion"},
  {ID = 2336, Name_Lang_enUS = "Elixir of Tongues"},
  {ID = 2337, Name_Lang_enUS = "Lesser Healing Potion"},
  {ID = 2362, Name_Lang_enUS = "Create Spellstone"},
  {ID = 2366, Name_Lang_enUS = "Herb Gathering"},
  {ID = 2367, Name_Lang_enUS = "Lesser Strength"},
  {ID = 2368, Name_Lang_enUS = "Herb Gathering"},
  {ID = 2369, Name_Lang_enUS = "Herb Gathering"},
  {ID = 2370, Name_Lang_enUS = "Rejuvenation Potion"},
  {ID = 2371, Name_Lang_enUS = "Herb Gathering"},
  {ID = 2372, Name_Lang_enUS = "Apprentice Herbalist"},
  {ID = 2373, Name_Lang_enUS = "Journeyman Herbalist"},
  {ID = 2374, Name_Lang_enUS = "Lesser Agility"},
  {ID = 2376, Name_Lang_enUS = "Lesser Intellect"},
  {ID = 2378, Name_Lang_enUS = "Health"},
  {ID = 2379, Name_Lang_enUS = "Speed"},
  {ID = 2380, Name_Lang_enUS = "Resistance"},
  {ID = 2381, Name_Lang_enUS = "Resistance (OLD)"},
  {ID = 2382, Name_Lang_enUS = "Generic"},
  {ID = 2383, Name_Lang_enUS = "Find Herbs"},
  {ID = 2385, Name_Lang_enUS = "Brown Linen Vest"},
  {ID = 2386, Name_Lang_enUS = "Linen Boots"},
  {ID = 2387, Name_Lang_enUS = "Linen Cloak"},
  {ID = 2389, Name_Lang_enUS = "Red Linen Robe"},
  {ID = 2392, Name_Lang_enUS = "Red Linen Shirt"},
  {ID = 2393, Name_Lang_enUS = "White Linen Shirt"},
  {ID = 2394, Name_Lang_enUS = "Blue Linen Shirt"},
  {ID = 2395, Name_Lang_enUS = "Barbaric Linen Vest"},
  {ID = 2396, Name_Lang_enUS = "Green Linen Shirt"},
  {ID = 2397, Name_Lang_enUS = "Reinforced Linen Cape"},
  {ID = 2399, Name_Lang_enUS = "Green Woolen Vest"},
  {ID = 2400, Name_Lang_enUS = "Transfer Power"},
  {ID = 2401, Name_Lang_enUS = "Woolen Boots"},
  {ID = 2402, Name_Lang_enUS = "Woolen Cape"},
  {ID = 2403, Name_Lang_enUS = "Gray Woolen Robe"},
  {ID = 2406, Name_Lang_enUS = "Gray Woolen Shirt"},
  {ID = 2425, Name_Lang_enUS = "Spotted"},
  {ID = 2426, Name_Lang_enUS = "Base Stealth"},
  {ID = 2442, Name_Lang_enUS = "Smashing Blow"},
  {ID = 2443, Name_Lang_enUS = "Smashing Blow II"},
  {ID = 2444, Name_Lang_enUS = "Smashing Blow III"},
  {ID = 2446, Name_Lang_enUS = "Smashing Blow V"},
  {ID = 2457, Name_Lang_enUS = "Battle Stance"},
  {ID = 2458, Name_Lang_enUS = "Berserker Stance"},
  {ID = 2479, Name_Lang_enUS = "Honorless Target"},
  {ID = 2481, Name_Lang_enUS = "Find Treasure"},
  {ID = 2484, Name_Lang_enUS = "Earthbind Totem"},
  {ID = 2538, Name_Lang_enUS = "Charred Wolf Meat"},
  {ID = 2539, Name_Lang_enUS = "Spiced Wolf Meat"},
  {ID = 2540, Name_Lang_enUS = "Roasted Boar Meat"},
  {ID = 2541, Name_Lang_enUS = "Coyote Steak"},
  {ID = 2542, Name_Lang_enUS = "Goretusk Liver Pie"},
  {ID = 2543, Name_Lang_enUS = "Westfall Stew"},
  {ID = 2544, Name_Lang_enUS = "Crab Cake"},
  {ID = 2545, Name_Lang_enUS = "Cooked Crab Claw"},
  {ID = 2546, Name_Lang_enUS = "Dry Pork Ribs"},
  {ID = 2547, Name_Lang_enUS = "Redridge Goulash"},
  {ID = 2548, Name_Lang_enUS = "Succulent Pork Ribs"},
  {ID = 2549, Name_Lang_enUS = "Seasoned Wolf Kabob"},
  {ID = 2550, Name_Lang_enUS = "Cooking"},
  {ID = 2551, Name_Lang_enUS = "Apprentice Cook"},
  {ID = 2552, Name_Lang_enUS = "QA Expert Cook"},
  {ID = 2565, Name_Lang_enUS = "Shield Block"},
  {ID = 2567, Name_Lang_enUS = "Thrown"},
  {ID = 2575, Name_Lang_enUS = "Mining"},
  {ID = 2576, Name_Lang_enUS = "Mining"},
  {ID = 2580, Name_Lang_enUS = "Find Minerals"},
  {ID = 2581, Name_Lang_enUS = "Apprentice Miner"},
  {ID = 2582, Name_Lang_enUS = "Journeyman Miner"},
  {ID = 2583, Name_Lang_enUS = "Debug Spell Reflection"},
  {ID = 2584, Name_Lang_enUS = "Waiting to Resurrect"},
  {ID = 2585, Name_Lang_enUS = "Eye of Kilrogg Passive (DND)"},
  {ID = 2589, Name_Lang_enUS = "Backstab"},
  {ID = 2590, Name_Lang_enUS = "Backstab"},
  {ID = 2591, Name_Lang_enUS = "Backstab"},
  {ID = 2596, Name_Lang_enUS = "Touch of the Black Claw"},
  {ID = 2597, Name_Lang_enUS = "Rejuvenation Potion"},
  {ID = 2598, Name_Lang_enUS = "Rejuvenation (OLD)"},
  {ID = 2599, Name_Lang_enUS = "Rejuvenation Potion"},
  {ID = 2600, Name_Lang_enUS = "Rejuvenation Potion"},
  {ID = 2601, Name_Lang_enUS = "Fire Shield III"},
  {ID = 2602, Name_Lang_enUS = "Fire Shield IV"},
  {ID = 2605, Name_Lang_enUS = "Sharpen Blade"},
  {ID = 2606, Name_Lang_enUS = "Shock"},
  {ID = 2607, Name_Lang_enUS = "Shock"},
  {ID = 2608, Name_Lang_enUS = "Shock"},
  {ID = 2609, Name_Lang_enUS = "Shock"},
  {ID = 2610, Name_Lang_enUS = "Shock"},
  {ID = 2626, Name_Lang_enUS = "Lightning Bolt Proc V"},
  {ID = 2629, Name_Lang_enUS = "Dagger Strike III (Disabled)"},
  {ID = 2630, Name_Lang_enUS = "Dagger Strike IV (Disabled)"},
  {ID = 2633, Name_Lang_enUS = "Dagger Strike III"},
  {ID = 2634, Name_Lang_enUS = "Dagger Strike IV"},
  {ID = 2636, Name_Lang_enUS = "Dagger Strike V"},
  {ID = 2637, Name_Lang_enUS = "Hibernate"},
  {ID = 2639, Name_Lang_enUS = "Food"},
  {ID = 2641, Name_Lang_enUS = "Dismiss Pet"},
  {ID = 2643, Name_Lang_enUS = "Multi-Shot"},
  {ID = 2645, Name_Lang_enUS = "Ghost Wolf"},
  {ID = 2647, Name_Lang_enUS = "Freeze III PROC"},
  {ID = 2649, Name_Lang_enUS = "Growl"},
  {ID = 2650, Name_Lang_enUS = "Tame Pet (TEST)"},
  {ID = 2653, Name_Lang_enUS = "Damage 100 (TEST)"},
  {ID = 2654, Name_Lang_enUS = "Summon Tamed (TEST)"},
  {ID = 2656, Name_Lang_enUS = "Smelting"},
  {ID = 2657, Name_Lang_enUS = "Smelt Copper"},
  {ID = 2658, Name_Lang_enUS = "Smelt Silver"},
  {ID = 2659, Name_Lang_enUS = "Smelt Bronze"},
  {ID = 2660, Name_Lang_enUS = "Rough Sharpening Stone"},
  {ID = 2661, Name_Lang_enUS = "Copper Chain Belt"},
  {ID = 2662, Name_Lang_enUS = "Copper Chain Pants"},
  {ID = 2663, Name_Lang_enUS = "Copper Bracers"},
  {ID = 2664, Name_Lang_enUS = "Runed Copper Bracers"},
  {ID = 2665, Name_Lang_enUS = "Coarse Sharpening Stone"},
  {ID = 2666, Name_Lang_enUS = "Runed Copper Belt"},
  {ID = 2667, Name_Lang_enUS = "Runed Copper Breastplate"},
  {ID = 2668, Name_Lang_enUS = "Rough Bronze Leggings"},
  {ID = 2670, Name_Lang_enUS = "Rough Bronze Cuirass"},
  {ID = 2671, Name_Lang_enUS = "Rough Bronze Bracers"},
  {ID = 2672, Name_Lang_enUS = "Patterned Bronze Bracers"},
  {ID = 2673, Name_Lang_enUS = "Silvered Bronze Breastplate"},
  {ID = 2674, Name_Lang_enUS = "Heavy Sharpening Stone"},
  {ID = 2675, Name_Lang_enUS = "Shining Silver Breastplate"},
  {ID = 2676, Name_Lang_enUS = "Pulverize"},
  {ID = 2687, Name_Lang_enUS = "Bloodrage"},
  {ID = 2691, Name_Lang_enUS = "Mana Burn"},
  {ID = 2737, Name_Lang_enUS = "Copper Mace"},
  {ID = 2738, Name_Lang_enUS = "Copper Axe"},
  {ID = 2739, Name_Lang_enUS = "Copper Shortsword"},
  {ID = 2740, Name_Lang_enUS = "Bronze Mace"},
  {ID = 2741, Name_Lang_enUS = "Bronze Axe"},
  {ID = 2742, Name_Lang_enUS = "Bronze Shortsword"},
  {ID = 2763, Name_Lang_enUS = "INVIS Only ON"},
  {ID = 2764, Name_Lang_enUS = "Throw"},
  {ID = 2765, Name_Lang_enUS = "SHOWLABEL Only ON"},
  {ID = 2766, Name_Lang_enUS = "KJORDAN (TEST)"},
  {ID = 2767, Name_Lang_enUS = "Shadow Word: Pain"},
  {ID = 2782, Name_Lang_enUS = "Remove Curse"},
  {ID = 2791, Name_Lang_enUS = "Power Word: Fortitude"},
  {ID = 2795, Name_Lang_enUS = "Beer Basted Boar Ribs"},
  {ID = 2800, Name_Lang_enUS = "Lay on Hands"},
  {ID = 2812, Name_Lang_enUS = "Holy Wrath"},
  {ID = 2816, Name_Lang_enUS = "Bark of Doom"},
  {ID = 2817, Name_Lang_enUS = "Teach Bark of Doom"},
  {ID = 2818, Name_Lang_enUS = "Deadly Poison"},
  {ID = 2819, Name_Lang_enUS = "Deadly Poison II"},
  {ID = 2823, Name_Lang_enUS = "Deadly Poison"},
  {ID = 2824, Name_Lang_enUS = "Deadly Poison II"},
  {ID = 2825, Name_Lang_enUS = "Bloodlust"},
  {ID = 2828, Name_Lang_enUS = "Sharpen Blade"},
  {ID = 2829, Name_Lang_enUS = "Sharpen Blade II"},
  {ID = 2830, Name_Lang_enUS = "Sharpen Blade III"},
  {ID = 2831, Name_Lang_enUS = "Armor +8"},
  {ID = 2832, Name_Lang_enUS = "Armor +16"},
  {ID = 2833, Name_Lang_enUS = "Armor +24"},
  {ID = 2834, Name_Lang_enUS = "Periodic Thunderclap"},
  {ID = 2836, Name_Lang_enUS = "Detect Traps"},
  {ID = 2842, Name_Lang_enUS = "Poisons"},
  {ID = 2850, Name_Lang_enUS = "Parry!"},
  {ID = 2855, Name_Lang_enUS = "Detect Magic"},
  {ID = 2860, Name_Lang_enUS = "Chain Lightning"},
  {ID = 2871, Name_Lang_enUS = "Nullify Disease"},
  {ID = 2880, Name_Lang_enUS = "Stun"},
  {ID = 2881, Name_Lang_enUS = "Light Leather"},
  {ID = 2882, Name_Lang_enUS = "Bear Form (PT) (NYI)"},
  {ID = 2893, Name_Lang_enUS = "Abolish Poison"},
  {ID = 2894, Name_Lang_enUS = "Fire Elemental Totem"},
  {ID = 2895, Name_Lang_enUS = "Wrath of Air Totem"},
  {ID = 2908, Name_Lang_enUS = "Soothe Animal"},
  {ID = 2912, Name_Lang_enUS = "Starfire"},
  {ID = 2941, Name_Lang_enUS = "Immolate"},
  {ID = 2944, Name_Lang_enUS = "Devouring Plague"},
  {ID = 2947, Name_Lang_enUS = "Fire Shield"},
  {ID = 2948, Name_Lang_enUS = "Scorch"},
  {ID = 2949, Name_Lang_enUS = "Fire Shield"},
  {ID = 2950, Name_Lang_enUS = "Anti-Holy"},
  {ID = 2963, Name_Lang_enUS = "Bolt of Linen Cloth"},
  {ID = 2964, Name_Lang_enUS = "Bolt of Woolen Cloth"},
  {ID = 2969, Name_Lang_enUS = "Aura Leech (PT)"},
  {ID = 2972, Name_Lang_enUS = "Detect Invisibility"},
  {ID = 2973, Name_Lang_enUS = "Raptor Strike"},
  {ID = 2974, Name_Lang_enUS = "Wing Clip"},
  {ID = 2975, Name_Lang_enUS = "Claw"},
  {ID = 2976, Name_Lang_enUS = "Claw"},
  {ID = 2977, Name_Lang_enUS = "Claw"},
  {ID = 2980, Name_Lang_enUS = "Claw"},
  {ID = 2981, Name_Lang_enUS = "Claw"},
  {ID = 2982, Name_Lang_enUS = "Claw"},
  {ID = 2983, Name_Lang_enUS = "Sprint"},
  {ID = 2995, Name_Lang_enUS = "Poisons"},
  {ID = 3007, Name_Lang_enUS = "Longshot III"},
  {ID = 3009, Name_Lang_enUS = "Claw"},
  {ID = 3010, Name_Lang_enUS = "Claw"},
  {ID = 3011, Name_Lang_enUS = "Fire Shot"},
  {ID = 3017, Name_Lang_enUS = "Immune Effect (TEST)"},
  {ID = 3018, Name_Lang_enUS = "Shoot"},
  {ID = 3019, Name_Lang_enUS = "Frenzy"},
  {ID = 3023, Name_Lang_enUS = "Debuff Nature (TEST)"},
  {ID = 3025, Name_Lang_enUS = "Cat Form (Passive)"},
  {ID = 3026, Name_Lang_enUS = "Use Soulstone"},
  {ID = 3029, Name_Lang_enUS = "Claw"},
  {ID = 3034, Name_Lang_enUS = "Viper Sting"},
  {ID = 3043, Name_Lang_enUS = "Scorpid Sting"},
  {ID = 3044, Name_Lang_enUS = "Arcane Shot"},
  {ID = 3045, Name_Lang_enUS = "Rapid Fire"},
  {ID = 3050, Name_Lang_enUS = "Detect"},
  {ID = 3052, Name_Lang_enUS = "Fire Shield Effect"},
  {ID = 3053, Name_Lang_enUS = "Fire Shield Effect II"},
  {ID = 3054, Name_Lang_enUS = "Fire Shield Effect III"},
  {ID = 3055, Name_Lang_enUS = "Fire Shield Effect IV"},
  {ID = 3100, Name_Lang_enUS = "Blacksmithing"},
  {ID = 3101, Name_Lang_enUS = "Alchemy"},
  {ID = 3102, Name_Lang_enUS = "Cooking"},
  {ID = 3104, Name_Lang_enUS = "Leatherworking"},
  {ID = 3105, Name_Lang_enUS = "Curse of Stalvan"},
  {ID = 3106, Name_Lang_enUS = "Aura of Rot"},
  {ID = 3107, Name_Lang_enUS = "Summon Eliza's Guard"},
  {ID = 3108, Name_Lang_enUS = "Touch of Death"},
  {ID = 3109, Name_Lang_enUS = "Presence of Death"},
  {ID = 3110, Name_Lang_enUS = "Firebolt"},
  {ID = 3111, Name_Lang_enUS = "Mend Pet"},
  {ID = 3112, Name_Lang_enUS = "Enhance Blunt Weapon"},
  {ID = 3113, Name_Lang_enUS = "Enhance Blunt Weapon II"},
  {ID = 3114, Name_Lang_enUS = "Enhance Blunt Weapon III"},
  {ID = 3115, Name_Lang_enUS = "Rough Weightstone"},
  {ID = 3116, Name_Lang_enUS = "Coarse Weightstone"},
  {ID = 3117, Name_Lang_enUS = "Heavy Weightstone"},
  {ID = 3120, Name_Lang_enUS = "Sol L"},
  {ID = 3121, Name_Lang_enUS = "Kev"},
  {ID = 3124, Name_Lang_enUS = "Parry"},
  {ID = 3127, Name_Lang_enUS = "Parry"},
  {ID = 3129, Name_Lang_enUS = "Frost Breath"},
  {ID = 3130, Name_Lang_enUS = "Ice Claw"},
  {ID = 3131, Name_Lang_enUS = "Frost Breath"},
  {ID = 3132, Name_Lang_enUS = "Chilling Breath"},
  {ID = 3136, Name_Lang_enUS = "Frenzied Command"},
  {ID = 3137, Name_Lang_enUS = "Abolish Poison Effect"},
  {ID = 3140, Name_Lang_enUS = "Fireball"},
  {ID = 3143, Name_Lang_enUS = "Glacial Roar"},
  {ID = 3145, Name_Lang_enUS = "Icy Grasp"},
  {ID = 3146, Name_Lang_enUS = "Daunting Growl"},
  {ID = 3147, Name_Lang_enUS = "Rend Flesh"},
  {ID = 3148, Name_Lang_enUS = "Head Crack"},
  {ID = 3149, Name_Lang_enUS = "Furious Howl"},
  {ID = 3150, Name_Lang_enUS = "Rabies"},
  {ID = 3151, Name_Lang_enUS = "Crazed Hunger"},
  {ID = 3157, Name_Lang_enUS = "Lesser Agility"},
  {ID = 3158, Name_Lang_enUS = "Lesser Agility"},
  {ID = 3159, Name_Lang_enUS = "Agility"},
  {ID = 3160, Name_Lang_enUS = "Agility"},
  {ID = 3161, Name_Lang_enUS = "Lesser Strength"},
  {ID = 3162, Name_Lang_enUS = "Lesser Strength"},
  {ID = 3163, Name_Lang_enUS = "Strength"},
  {ID = 3164, Name_Lang_enUS = "Strength"},
  {ID = 3165, Name_Lang_enUS = "Lesser Intellect"},
  {ID = 3166, Name_Lang_enUS = "Lesser Intellect"},
  {ID = 3167, Name_Lang_enUS = "Intellect"},
  {ID = 3168, Name_Lang_enUS = "Intellect"},
  {ID = 3169, Name_Lang_enUS = "Invulnerability"},
  {ID = 3170, Name_Lang_enUS = "Weak Troll's Blood Elixir"},
  {ID = 3171, Name_Lang_enUS = "Elixir of Wisdom"},
  {ID = 3172, Name_Lang_enUS = "Minor Magic Resistance Potion"},
  {ID = 3173, Name_Lang_enUS = "Lesser Mana Potion"},
  {ID = 3174, Name_Lang_enUS = "Potion of Curing"},
  {ID = 3175, Name_Lang_enUS = "Limited Invulnerability Potion"},
  {ID = 3176, Name_Lang_enUS = "Strong Troll's Blood Elixir"},
  {ID = 3177, Name_Lang_enUS = "Elixir of Defense"},
  {ID = 3188, Name_Lang_enUS = "Elixir of Ogre's Strength"},
  {ID = 3204, Name_Lang_enUS = "Sapper Explode"},
  {ID = 3205, Name_Lang_enUS = "Sol M"},
  {ID = 3206, Name_Lang_enUS = "Sol H"},
  {ID = 3207, Name_Lang_enUS = "Sol U"},
  {ID = 3219, Name_Lang_enUS = "Weak Troll's Blood Elixir"},
  {ID = 3220, Name_Lang_enUS = "Armor"},
  {ID = 3221, Name_Lang_enUS = "Regeneration"},
  {ID = 3222, Name_Lang_enUS = "Strong Troll's Blood Elixir"},
  {ID = 3223, Name_Lang_enUS = "Major Troll's Blood Elixir"},
  {ID = 3229, Name_Lang_enUS = "Quick Bloodlust"},
  {ID = 3230, Name_Lang_enUS = "Elixir of Minor Agility"},
  {ID = 3231, Name_Lang_enUS = "QAEnchant Cloak +3 Agility"},
  {ID = 3232, Name_Lang_enUS = "Gouge Stun Test"},
  {ID = 3233, Name_Lang_enUS = "Evil Eye"},
  {ID = 3234, Name_Lang_enUS = "Disease Touch"},
  {ID = 3235, Name_Lang_enUS = "Rancid Blood"},
  {ID = 3237, Name_Lang_enUS = "Curse of Thule"},
  {ID = 3238, Name_Lang_enUS = "Nimble Reflexes"},
  {ID = 3240, Name_Lang_enUS = "Bloody Explosion"},
  {ID = 3242, Name_Lang_enUS = "Ravage"},
  {ID = 3243, Name_Lang_enUS = "Life Harvest"},
  {ID = 3245, Name_Lang_enUS = "Chicken"},
  {ID = 3246, Name_Lang_enUS = "Chicken Other"},
  {ID = 3247, Name_Lang_enUS = "Agonizing Pain"},
  {ID = 3248, Name_Lang_enUS = "Improved Blocking"},
  {ID = 3252, Name_Lang_enUS = "Shred"},
  {ID = 3256, Name_Lang_enUS = "Plague Cloud"},
  {ID = 3258, Name_Lang_enUS = "Savage Rage"},
  {ID = 3260, Name_Lang_enUS = "Violet Shield Effect"},
  {ID = 3261, Name_Lang_enUS = "Ignite"},
  {ID = 3263, Name_Lang_enUS = "Touch of Ravenclaw"},
  {ID = 3264, Name_Lang_enUS = "Blood Howl"},
  {ID = 3267, Name_Lang_enUS = "First Aid"},
  {ID = 3268, Name_Lang_enUS = "First Aid"},
  {ID = 3269, Name_Lang_enUS = "Blessing of Thule"},
  {ID = 3271, Name_Lang_enUS = "Fatigued"},
  {ID = 3273, Name_Lang_enUS = "First Aid"},
  {ID = 3274, Name_Lang_enUS = "First Aid"},
  {ID = 3275, Name_Lang_enUS = "Linen Bandage"},
  {ID = 3276, Name_Lang_enUS = "Heavy Linen Bandage"},
  {ID = 3277, Name_Lang_enUS = "Wool Bandage"},
  {ID = 3278, Name_Lang_enUS = "Heavy Wool Bandage"},
  {ID = 3279, Name_Lang_enUS = "Apprentice First Aid"},
  {ID = 3280, Name_Lang_enUS = "Journeyman First Aid"},
  {ID = 3284, Name_Lang_enUS = "Violent Shield"},
  {ID = 3286, Name_Lang_enUS = "Bind"},
  {ID = 3287, Name_Lang_enUS = "Ghoul Form"},
  {ID = 3288, Name_Lang_enUS = "Moss Hide"},
  {ID = 3292, Name_Lang_enUS = "Heavy Copper Broadsword"},
  {ID = 3293, Name_Lang_enUS = "Copper Battle Axe"},
  {ID = 3294, Name_Lang_enUS = "Thick War Axe"},
  {ID = 3295, Name_Lang_enUS = "Deadly Bronze Poniard"},
  {ID = 3296, Name_Lang_enUS = "Heavy Bronze Mace"},
  {ID = 3297, Name_Lang_enUS = "Mighty Iron Hammer"},
  {ID = 3304, Name_Lang_enUS = "Smelt Tin"},
  {ID = 3307, Name_Lang_enUS = "Smelt Iron"},
  {ID = 3308, Name_Lang_enUS = "Smelt Gold"},
  {ID = 3319, Name_Lang_enUS = "Copper Chain Boots"},
  {ID = 3320, Name_Lang_enUS = "Rough Grinding Stone"},
  {ID = 3321, Name_Lang_enUS = "Copper Chain Vest"},
  {ID = 3322, Name_Lang_enUS = "Rancid Blood"},
  {ID = 3323, Name_Lang_enUS = "Runed Copper Gauntlets"},
  {ID = 3324, Name_Lang_enUS = "Runed Copper Pants"},
  {ID = 3325, Name_Lang_enUS = "Gemmed Copper Gauntlets"},
  {ID = 3326, Name_Lang_enUS = "Coarse Grinding Stone"},
  {ID = 3328, Name_Lang_enUS = "Rough Bronze Shoulders"},
  {ID = 3329, Name_Lang_enUS = "Creature - Frog Form"},
  {ID = 3330, Name_Lang_enUS = "Silvered Bronze Shoulders"},
  {ID = 3331, Name_Lang_enUS = "Silvered Bronze Boots"},
  {ID = 3332, Name_Lang_enUS = "Slow Poison"},
  {ID = 3333, Name_Lang_enUS = "Silvered Bronze Gauntlets"},
  {ID = 3334, Name_Lang_enUS = "Green Iron Boots"},
  {ID = 3335, Name_Lang_enUS = "Dark Sludge"},
  {ID = 3336, Name_Lang_enUS = "Green Iron Gauntlets"},
  {ID = 3337, Name_Lang_enUS = "Heavy Grinding Stone"},
  {ID = 3338, Name_Lang_enUS = "Rancid Ooze"},
  {ID = 3339, Name_Lang_enUS = "Rancid Ooze Effect"},
  {ID = 3355, Name_Lang_enUS = "Freezing Trap Effect"},
  {ID = 3356, Name_Lang_enUS = "Flame Lash"},
  {ID = 3358, Name_Lang_enUS = "Leech Poison"},
  {ID = 3359, Name_Lang_enUS = "Drink Potion"},
  {ID = 3360, Name_Lang_enUS = "Curse of the Eye"},
  {ID = 3361, Name_Lang_enUS = "Dummy NPC Summon"},
  {ID = 3362, Name_Lang_enUS = "Dire Wolf (TEST)"},
  {ID = 3363, Name_Lang_enUS = "Nether Drake"},
  {ID = 3365, Name_Lang_enUS = "Opening"},
  {ID = 3366, Name_Lang_enUS = "Opening"},
  {ID = 3368, Name_Lang_enUS = "Drink Minor Potion"},
  {ID = 3369, Name_Lang_enUS = "Potion Strength II"},
  {ID = 3370, Name_Lang_enUS = "Crocolisk Steak"},
  {ID = 3371, Name_Lang_enUS = "Blood Sausage"},
  {ID = 3372, Name_Lang_enUS = "Murloc Fin Soup"},
  {ID = 3373, Name_Lang_enUS = "Crocolisk Gumbo"},
  {ID = 3376, Name_Lang_enUS = "Curiously Tasty Omelet"},
  {ID = 3377, Name_Lang_enUS = "Gooey Spider Cake"},
  {ID = 3385, Name_Lang_enUS = "Boar Charge"},
  {ID = 3387, Name_Lang_enUS = "Rage of Thule"},
  {ID = 3388, Name_Lang_enUS = "Deadly Leech Poison"},
  {ID = 3389, Name_Lang_enUS = "Ward of the Eye"},
  {ID = 3390, Name_Lang_enUS = "Helcular's Spawn"},
  {ID = 3391, Name_Lang_enUS = "Thrash"},
  {ID = 3393, Name_Lang_enUS = "Consume Flesh"},
  {ID = 3394, Name_Lang_enUS = "Consume Flesh"},
  {ID = 3396, Name_Lang_enUS = "Corrosive Poison"},
  {ID = 3397, Name_Lang_enUS = "Big Bear Steak"},
  {ID = 3398, Name_Lang_enUS = "Hot Lion Chops"},
  {ID = 3399, Name_Lang_enUS = "Tasty Lion Steak"},
  {ID = 3400, Name_Lang_enUS = "Soothing Turtle Bisque"},
  {ID = 3405, Name_Lang_enUS = "Soul Rend"},
  {ID = 3407, Name_Lang_enUS = "Rune of Opening"},
  {ID = 3408, Name_Lang_enUS = "Crippling Poison"},
  {ID = 3409, Name_Lang_enUS = "Crippling Poison"},
  {ID = 3411, Name_Lang_enUS = "Intervene"},
  {ID = 3412, Name_Lang_enUS = "Journeyman Cook"},
  {ID = 3413, Name_Lang_enUS = "Cooking"},
  {ID = 3416, Name_Lang_enUS = "Fiend Fury"},
  {ID = 3417, Name_Lang_enUS = "Thrash"},
  {ID = 3418, Name_Lang_enUS = "Improved Blocking"},
  {ID = 3419, Name_Lang_enUS = "Improved Blocking"},
  {ID = 3424, Name_Lang_enUS = "Tainted Howl"},
  {ID = 3427, Name_Lang_enUS = "Infected Wound"},
  {ID = 3428, Name_Lang_enUS = "Summon Flesh Eating Worms"},
  {ID = 3429, Name_Lang_enUS = "Plague Mind"},
  {ID = 3436, Name_Lang_enUS = "Wandering Plague"},
  {ID = 3439, Name_Lang_enUS = "Wandering Plague"},
  {ID = 3440, Name_Lang_enUS = "MACESTAFFSPECIAL (DND)"},
  {ID = 3442, Name_Lang_enUS = "Enslave"},
  {ID = 3443, Name_Lang_enUS = "Enchanted Quickness"},
  {ID = 3446, Name_Lang_enUS = "Ravage"},
  {ID = 3447, Name_Lang_enUS = "Healing Potion"},
  {ID = 3448, Name_Lang_enUS = "Lesser Invisibility Potion"},
  {ID = 3449, Name_Lang_enUS = "Shadow Oil"},
  {ID = 3450, Name_Lang_enUS = "Elixir of Fortitude"},
  {ID = 3451, Name_Lang_enUS = "Major Troll's Blood Elixir"},
  {ID = 3452, Name_Lang_enUS = "Mana Potion"},
  {ID = 3453, Name_Lang_enUS = "Elixir of Detect Lesser Invisibility"},
  {ID = 3454, Name_Lang_enUS = "Frost Oil"},
  {ID = 3464, Name_Lang_enUS = "Alchemy"},
  {ID = 3465, Name_Lang_enUS = "Expert Alchemist"},
  {ID = 3466, Name_Lang_enUS = "Kick"},
  {ID = 3472, Name_Lang_enUS = "Holy Light"},
  {ID = 3477, Name_Lang_enUS = "Spirit Steal"},
  {ID = 3485, Name_Lang_enUS = "Wail of Nightlash"},
  {ID = 3488, Name_Lang_enUS = "Felstrom Resurrection"},
  {ID = 3490, Name_Lang_enUS = "Frenzied Rage"},
  {ID = 3491, Name_Lang_enUS = "Big Bronze Knife"},
  {ID = 3492, Name_Lang_enUS = "Hardened Iron Shortsword"},
  {ID = 3493, Name_Lang_enUS = "Jade Serpentblade"},
  {ID = 3494, Name_Lang_enUS = "Solid Iron Maul"},
  {ID = 3495, Name_Lang_enUS = "Golden Iron Destroyer"},
  {ID = 3496, Name_Lang_enUS = "Moonsteel Broadsword"},
  {ID = 3497, Name_Lang_enUS = "Frost Tiger Blade"},
  {ID = 3498, Name_Lang_enUS = "Massive Iron Axe"},
  {ID = 3499, Name_Lang_enUS = "Summon Sloth"},
  {ID = 3500, Name_Lang_enUS = "Shadow Crescent Axe"},
}

return spells
